name: security workflow

on:
  workflow_call:
    inputs:
      image_location:
        required: true
        type: string

jobs:
  scan-and-sign:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: app
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.REGISTRY_URL}}
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Pull image
        run: |
          docker pull ${{inputs.image_location}}
      - name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: ${{inputs.image_location}}
